#+Title: HoEaHCC, notes on

Best enjoyed [[https://unintuitive.org/HoEaHCC/README.html][here]]! The repo is [[https://github.com/stnbu/HoEaHCC][here]].

* Definitions
** Long Definitions

*** Group

A group satisfies the axioms...

- /Closure/ :: If $x$ and $y$ are two elements in a group, $G$, then $x . y$ is also in $G$.
- /Associativity/ :: If $x$, $y$ and $z$ are in group $G$, then $x . (y . z) = (x . y) . z$
- /Invertibility/ :: For every $x$ in $G$, there exists some $y$ in $G$, such that; $x . y = y . x$
- /Identity/ :: For any element $x$ in $G$, there exists an element $I$ in $G$, such that: $x . I = I . x$, where $I$ is called the identity element of $G$.

Axiomatical corollaries and properties that groups can have...

- The unit of a group is unique [wait, are unit and identity always interchangeable...?]
- The inverse of an element x, denoted by $x^{−1}$, is unique
- If abelian, the inverse of x is usually denoted by −x
- A group $G$ is cyclic if there is $x ∈ G$ such that $\langle x \rangle = G$
- Every subgroup of a cyclic group G is also cyclic.
- If $G$ is cyclic and of order $n$, then for each divisor $d$ of $n$, $G$ contains exactly one cyclic subgroup of order $d$.

**** Subgroup

Let $G$ be a group. A subgroup $H$ of $G$ is a subset of $G$ containing the unit element $e$ and such that
- for all $x,y ∈ H$ one has xy ∈ H
- if $x ∈ H$ then also $x^{−1} ∈ H$.

 tl;dr -- A subgroup is exactly what it sounds like: A group formed by some elements of a larger group.

[[https://mathworld.wolfram.com/LagrangesGroupTheorem.html][Lagrange Theorem]]

Let $G$ be a finite group and $H$ be a subgroup of $G$. Then the order of $H$ divides the order of $G$. As a consequence, the order of every element [in $H$?] also divides the order of $G$.

$|G| = |H| \cdot (G:H)$

The order of $G$ equals the order of $H$ times the number of (left) cosets of $H$.

**** Abelian Group

 - Group with commutativity.

**** Equivalence classes and left/right cosets

Let $G$ be a group and $H$ be a subgroup of $G$.

For all $x, y ∈ G$, the relation $x∼y ∈ H$, if and only if $x^{−1}y ∈ H$ and $x ∼ y$ if and only if $yx^{−1} ∈ H$, is an equivalence relation.

An equivalence class for this relation is denoted by $xH = \{xh | h ∈ H\}$, respectively $Hx = \{hx | h ∈ H\}$ and are called respectively left and right /cosets/ of $H$. The numbers of classes for both relations are the same. This invariant is called the "index of $H$ in $G$" and is denoted by $[G : H]$.

**** Cayley's Theorem

Every group $G$ is isomorphic to a subgroup of the symmetric group $Sym(G)$ whose elements are the permutations of the underlying set of $G$

- Q :: "every group $G$ is isomorphic to a subgroup of the symmetric group on (the underlying set of) $G$." --> If that is the case, then isn't $Sym(G) = Sym(\mathbb{Z}_n)$ where $n = |G|$ ...? In other words, the group composition law is not part of this. This is only permuting $|G|$ symbols, right!? What gives.

*** Field

A field is a set on which addition, subtraction, multiplication, and division are defined and behave as the corresponding operations on rational and real numbers do.

**** Subfields and field extensions

A field extension is a pair of fields $E\subseteq F$ such that the operations of $E$ are those of $F$ restricted to $E$. In this case, $F$ is an extension field of $E$ and $E$ is a subfield of $F$.

*** Ring

"[R]ings are algebraic structures that generalize fields: multiplication need not be commutative and multiplicative inverses need not exist."

*** Discrete logarithm [problem]

In any group $G$, powers $b**k$ can be defined for all integers $k$, and the discrete logarithm $log_ba$ is an integer $k$ such that $b^k = a$.

The **problem** is that it's hard to find a $k$ given only $b$ and $a$.

In the book's notation we want a $k$ such that $[k]P = Q$, where $P$ is the generator (a point chosen on the curve that forms a group). $P$ is fundamental to the chosen curve's finite field. $Q$ is your "public key" and $k$ is your "private key" (probably wrong <---)

*** Homomorphism

Given two groups, $(G, ∗)$ and $(H, \odot)$, a group homomorphism from $(G, ∗)$ to $(H, \odot)$ is a function $h : G → H$ such that for all $u$ and $v$ in $G$ it holds that

$h(u*v)=h(u) \odot h(v)$

*** Isomorphism

Given two groups $(G,*)$ and $(H,\odot)$, a group isomorphism from $(G,∗)$ to $(H,\odot)$ is a bijective group homomorphism from $G$ to $H$. Spelled out, this means that a group isomorphism is a bijective function $f:G\to H$ such that for all $u$ and $v$ in $G$ it holds that

$f(u*v)=f(u) \odot f(v)$

The two groups $(G,∗)$ and $(H,⊙)$ are isomorphic if there exists an isomorphism from one to the other. This is written:

$(G,∗)≅(H,⊙)$

tl;dr -- An isomorphism is a homomorphism "in both directions" (yes?)

** Short Definitions

- decision problem :: is statement about input true or false. "Is this number prime?"

- computation problem :: do a computation for me. "What is the result of one divided by zero?"

- associative :: $(xy)z = x(yz)$

- commutative :: $xy = yx$

- transitive :: $x = y$ and $y = z$ $\implies x = z$

- cyclic :: there exists $x ∈ G$ such that $\langle x \rangle = G$ (I thought this was a feature of all [finite?] groups. Otherwise, they are "partitioned" [distinct]...I thought. Explore: finite non-cyclic groups.)

- image :: For a subset $R$ of $S$ the /image/ of $f(R)$ is the set of all $f(r)$ where $r ∈ R$.
  Comprehensible example time: If $S = \mathbb{Z}$ and $R = \mathbb{Z}_2$ and $f(n) = 2n$ then the /image/ of $f(R) = \mathbb{Z}_4$ ... yes?

- $\mathbb{Z}/n\mathbb{Z}$ ::
  As best "we" can tell: This is "integers that are multiples of $n$". If $n$ is five, then it means $[0, 5, 10, ...]$ _Or is it_ "the cyclic group of order $n$"? aka $[0, 1, 2, ...n-1]$ ...?

- $\langle x \rangle$ :: the set $\{x^n | n ∈ \mathbb{Z}\}$

- equivalence class :: Given a set $S$ and an equivalence relation $\sim$ on $S$, the /equivalence class/ of an element $a$ in $S$, denoted by $[a]$ is the set

        $\{ x \in S : x \sim a \}$

	[Isn't this incomplete? $\sim$ acting on $a,b \in S$ must also satisfy the axioms to be an /equivalence class/. Otherwise, it is a /setoid/.]

- conjugacy and equivalence :: elements $a$ and $b$ of a group are conjugate if there is an element $g$ in the group such that $b=g^{-1}ag$. This is an equivalence relation whose equivalence classes are called conjugacy classes.

- setoid :: A set together with its binary relation operator ("is $a$ /related/ to $b$ by our rule? yes/no$).

* What The Hell Is This

+ "One can formulate a computation problem from a decision problem." Really?
+ "On the other hand for elliptic curves no subexponential algorithm is known for the DLP" --> Is this the definition of an "elliptic curve"? or a property?
+ "Jacobians of curves of small genus"
+ "abstract cohomology theories and classical results from explicit class field theory are used for efficient implementations to count points on hyperelliptic curves" --> /only/ hyperelliptic curves?
+ Are there "points outside of a (EC) group that lead you /into/ a group?" -- the more I learn the more I wonder if the question makes sense. $[k]P$ is in the group /by definition/. So in that way there is no "starting outside the group". But what about starting with a different generator? can $[j]Q = [k]K$ for some $[j]Q$ that is outside of the group? err, grumble.
+ What's with this affine/projection stuff on P271?
+ "Common notations for the image of (x, y) under this mapping are x × y..." --> I am thrown by "image". That's not the same as "members x and y" wat? image? [We now think we know what "image" means and define it above 👆]
+ "The **group G is said to be** commutative or **abelian**, if the composition law is commutative. As previously mentioned, **the law is often denoted by + or ⊕ and the unit element by 0 in this case.**" --> wwhaaat? -- Are + and ⊕ interchangeable and /have nothing to do with/ commutativity? Is 0 the unit element /in the case/ of abelian groups? (only? yes but also?) -- questions about notation.
+ "Definition 2.6 Let $G$ be a group. An element $x ∈ G$ is of finite order if $\langle x \rangle$ is finite." --> Can there be infinite-order groups that have $x$ of finite order? And we are saying the /element/ is of finite order, yes?
+ "The group $S_n$ is solvable if and only if $n <= 4$. " NNeat!
+ "This is an essential part of the proof of the Abel–Ruffini theorem that shows that for every $n > 4$ there are polynomials of degree $n$ which are not solvable by radicals, that is, the solutions cannot be expressed by performing a finite number of operations of addition, subtraction, multiplication, division and root extraction on the polynomial's coefficients." --> sure sounds important
+ ${\displaystyle g=(1\ 2\ 5)(3\ 4)={\begin{pmatrix}1&2&3&4&5\\2&5&4&3&1\end{pmatrix}}.}$ --> I understand [[https://en.wikipedia.org/wiki/Symmetric_group#Multiplication][Cauchy's two-line notation]] but I do not understand e.g. $(1\ 2\ 5)(3\ 4)$. What dat?
+ "Given a set $S$, a composition law $×$ of $S$ into itself is a mapping from the Cartesian product $S × S$ to $S$. Common notations for the image of $(x, y)$ under this mapping are $x × y$, $x.y$ or simply $xy$. When the law is commutative, i.e., when the images of $(x, y)$ and $(y, x)$ under the composition law are the same for all $x, y ∈ S$, it is customary to denote it by $+$." --> My understanding of this is the "image of $x × y$" is the /single element/ resulting from the composition of $x$ and $y$ under $×$. Yes? An image can be one element. Is this what is meant? Why all the fancy "image" talk?
+ I would like a nice mnemonic for remembering the convention: $×$ is used for "just groups" and $+$ is used for abelian groups. Maybe: matrix multiplication is /not/ abelian (commutative) but matrix addition /is/ commutative.
+ "Let $G$ be a group. An element $x ∈ G$ is of finite order if $\langle x \rangle$ is finite. In this case, the order of x is $|\langle x \rangle|$, that is, the smallest positive integer $n$ such that $xn = e$. Otherwise, $x$ is of infinite order." --> Idle wonderment: 1) why not "iff"? 2) can a single group contain elements of both finite and infinite order? (seems like "no" and a meaningful exercise proof).
+ These (axioms for equivalence relation) are suspiciously analogous to the group axioms:
  - $a \sim a$ for all $a \in X$ (reflexivity)
  - $a \sim b$ implies $b \sim a$ for all $a,b \in X$ (symmetry)
  - if $a \sim b$ and $b \sim c$ then $a \sim c$ for all $a,b,c \in X$ (transitivity)
+ A ring "has addition and multiplication" and possibly they "behave as the corresponding operations on rational and real numbers" -- In "regular math", the multiplication operator is defined /in terms of/ the addition operator: $n . X == X + X + ... + X$  Is this generally true for fields? In "regular math" the aforementioned $n$ is /part of the same field/. If you have field elements $a$ and $b$, does it make sense to say $a . b$ is just $b$ added to itsel $a$ times? What does "$a$ times" mean when $a$ is some absract /thing/. What if $a$ is a matrix? Can one add $b$ to itself "$[(3, 2), (8, -7)]$ times" ...!!?

** Yes but why is $n^0=1$?

+ Take the infinite group $G = (\mathbb{Z}, +)$, consider its generated subgroup $H = \{ x^n | n \in \mathbb{Z}  \}$ (for any $n$ you like, say $2$). $H$ /does not contain the identity/. Right? Yes, we know that the identity is $0$. Suppose $\mathbb{Z}_?$ is an infinite group with the same (?) properties as $\mathbb{Z}$ and we choose $2_?$ as our generator. If $n=1$, we get the $2_?$; we apply the composition rule to the generator ($2_?$) /itself/ zero times ($n=1$ but we do zero operations/compositions: we just get $2_?$ back). If $n=2$ we get $4_?$. We know how to compose an element with nothing (we get the element itself). We know how to compose an element with itself $n>1$ times. How do we compose $2_?$ /zero times/ and get the identity: $0_?$ *without* looking at the math book and reading that "$n^0 = 1$ it is known". Put another way, how would I change [[https://github.com/stnbu/HoEaHCC/blob/1d12f97dfec9b35ab647d393fbff286c94a97bf4/play/generated_subgroup.py#L11][this python function]] so that "g[0] != g[1]" /without losing generalization/? Maybe there really is the idea of "plus-like" and "mul-like" operators outside of "regular numbers"

* Some resources; no promises

- https://loup-vaillant.fr/tutorials/cofactor
- https://cr.yp.to/ecdh/curve25519-20060209.pdf
- https://jeremykun.com/2014/03/13/programming-with-finite-fields/
- https://github.com/stnbu/finite-fields
- https://www.johndcook.com/blog/2019/02/19/addition-on-curve1174/
- https://trustica.cz/category/ecc/
- https://trustica.cz/2018/04/26/elliptic-curves-prime-order-curves/ [if this isn't an outlier from trustica ecc blogs, remove it]
- https://www.youtube.com/watch?v=mFVKuFZ29Fc <-- Gobsmakaroo!
- [[https://www.youtube.com/watch?v=RnqwFpyqJFw&list=PL8yHsr3EFj51pjBvvCPipgAT3SYpIiIsJ][Group Theory 101]]
- Let's circle back to [[https://mech.fsv.cvut.cz/~stransky/software/latexexpr/doc/][this]] sometime soon. No github repo, no setup.py, requires mucking about.
- [[https://faculty.atu.edu/mfinan/4033/absalg20.pdf][Cayley’s Theorem]]
- If you think symmetric groups are "simple" -- https://people.bath.ac.uk/masgcs/courses.bho/cycles.pdfTEST TEST
